defaults:
  - _self_

##########################################################
# Research question that the agents are going to explore #
##########################################################
copilot_mode: false # user will be asked to provide a research question and assistance
research_topic: null

# General settings
print_costs: true
verbose: true
compile_latex: false # requires pdflatex to be installed
language: English
max_steps: 100 # max number of steps for each phase, i.e. compute tolerance budget
paper_length: 3000 # best effort - actual length may vary based on workflow.papersolver_max_steps
api_keys:
  openai: null
  deepseek: null
  anthropic: null
  fireworks: null
  ollama: dummy-not-used

# State loading
resume:
  load_existing: false
  load_existing_path: null
  update_agent_state: false # update agent max steps, notes, and llm backend

# LLM settings
# ollama models need to be prefixed with `ollama:`
# fireworks models need to be prefixed with `fireworks:`
llm_backend: ollama:deepseek-r1:14b-qwen-distill-q8_0
ollama_host: http://localhost:11434

workflow:
  num_papers_lit_review: 5
  mlesolver_max_steps: 3
  papersolver_max_steps: 5

###################################################
###  LLM Backend used for the different phases  ###
###################################################
agent_models:
  literature_review: ${llm_backend}
  plan_formulation: ${llm_backend}
  data_preparation: ${llm_backend}
  running_experiments: ${llm_backend}
  results_interpretation: ${llm_backend}
  report_writing: ${llm_backend}
  report_refinement: ${llm_backend}

####################################################
###  Stages where human input will be requested  ###
####################################################
human_in_loop:
  literature_review: ${copilot_mode}
  plan_formulation: ${copilot_mode}
  data_preparation: ${copilot_mode}
  running_experiments: ${copilot_mode}
  results_interpretation: ${copilot_mode}
  report_writing: ${copilot_mode}
  report_refinement: ${copilot_mode}

task_notes:
  - phases: [plan formulation]
    notes:
      - "You should come up with a plan for TWO experiments."

  - phases: [running experiments]
    notes:
      - "I would recommend using a small dataset (approximately only 256 data points) to run experiments in order to save time. Do not use much more than this unless you have to or are running the final tests."

  - phases: [data preparation, running experiments]
    notes:
      - "You are running on a Linux system. You can use 'cuda' with PyTorch"
      - "Generate figures with very colorful and artistic design."
